# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2ade5b2a9823b5933616dd576accd1351d6e99d204a414c1e724791ef6373279d21f7b149686d06398bde14c991a4060e811469813454174ea0499d41a2ac0ee

test:
  secret_key_base: 79bd6d37430842fa0f61921011258bd440d549c203d37824f08d53591febc1a957a42f44cdf9939a83938e4207ea13df70e5cc20a886935b07781afb4b446c57

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
